/*======================================================================================
                                  DATABASE EXPLORATION
========================================================================================*/

--Explore all the objects in the Database 
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore all the columns in the Database 
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

/*======================================================================================
                                 DIMENSION EXPLORATION
========================================================================================*/

--Explore all Countries our Customers come from.
SELECT DISTINCT country FROM gold.dim_customers

--Explore all Categories "THE MAJOR DIVISIONS"
SELECT DISTINCT category, sub_category, product_name FROM gold.dim_products
ORDER BY 1,2,3

/*======================================================================================
                                 DATE EXPLORATION
========================================================================================*/

--Find the Date of the First and Last Order.
--How many Years/Months of Sales are available.

SELECT 
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(month, MIN(order_date), MAX(order_date)) AS order_range_years  
FROM gold.fact_sales

--Find the Youngest and Oldest customer.
SELECT 
MIN(birthday) AS oldest_birthdate,
DATEDIFF(year, MIN(birthday), GETDATE()) AS oldest_customer,
MAX(birthday) AS latest_birthdate,
DATEDIFF(year, MAX(birthday), GETDATE()) AS youngest_customer
FROM gold.dim_customers 

/*======================================================================================
                                 MEASURES EXPLORATION
========================================================================================*/

--Find the Total Sales
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales AS total_sales

--How many items are sold.
SELECT COUNT(quantity) AS total_quantity
FROM gold.fact_sales

--Find the Average selling Price.
SELECT AVG(price) AS average_selling_price
FROM gold.fact_sales

--Find the Total Number of Orders.
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales

--Find the Total Number of Customers.
SELECT COUNT(customer_key) AS total_customers
FROM gold.dim_customers

--Find the total Number of Customers that have placed an Order.
SELECT COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers

--Generate a report that shoes all key metrics of the business.
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales 
UNION ALL
SELECT 'Total Qunatity', SUM(quantity) FROM gold.fact_sales 
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total no. of orders', COUNT(DISTINCT order_date) FROM gold.fact_sales
UNION ALL
SELECT 'Total no. of products', COUNT(product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total no. of customers', COUNT(customer_key) FROM gold.dim_customers

/*======================================================================================
                                       MAGNITUDE
========================================================================================*/

--Find Total Customers by Country
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country 
ORDER BY total_customers DESC

--Find the Toatla Customers By Gender
SELECT 
gender ,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender 
ORDER BY total_customers DESC

--Find the Total Products by category.
SELECT 
category,
COUNT(DISTINCT product_name) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is the aaverage cost in each category.
SELECT 
category,
AVG(cost) AS average_cost
FROM gold.dim_products 
GROUP BY category
ORDER BY average_cost DESC 

--What is the Total Revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) AS total_revenue
FROM 
gold.dim_products p
JOIN gold.fact_sales f
ON p.product_key= f.product_key 
GROUP BY p.category
ORDER BY total_revenue DESC

--What is the Total Revenue generated by each customer?
SELECT 
DISTINCT c.customer_key,
c.firtsname,
c.lastname,
SUM(f.sales_amount) AS total_revenue
FROM 
gold.dim_customers c
JOIN gold.fact_sales f
ON c.customer_key= f.customer_key
GROUP BY 
c.customer_key,
c.firtsname,
c.lastname
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) AS total_revenue
FROM 
gold.dim_customers c
JOIN gold.fact_sales f
ON c.customer_key= f.customer_key
GROUP BY 
c.country
ORDER BY total_revenue DESC

/*======================================================================================
                                       RANKING
========================================================================================*/

--Which 5 Products generate the Highest revenue?
SELECT 
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM 
gold.dim_products p
JOIN gold.fact_sales f
ON p.product_key= f.product_key
GROUP BY 
p.product_name
ORDER BY total_revenue DESC

--Which are the tp 5 worst-performing products in terms of slaes?
SELECT TOP 5 
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM 
gold.dim_products p
JOIN gold.fact_sales f
ON p.product_key= f.product_key
GROUP BY 
p.product_name
ORDER BY total_revenue ASC

--Top 10 customers who have generated the highest revenue.
SELECT TOP 10 
c.customer_key,
c.firtsname,
c.lastname,
SUM(f.sales_amount) AS total_revenue
FROM 
gold.dim_customers c
JOIN gold.fact_sales f
ON c.customer_key= f.customer_key
GROUP BY 
c.customer_key,
c.firtsname,
c.lastname
ORDER BY total_revenue DESC

--The 3 cutomers with the fewest orders placed.
SELECT TOP 3
c.customer_key,
c.firtsname,
c.lastname,
COUNT(DISTINCT f.order_number) AS total_orders
FROM 
gold.dim_customers c
JOIN gold.fact_sales f
ON c.customer_key= f.customer_key
GROUP BY 
c.customer_key,
c.firtsname,
c.lastname
ORDER BY total_orders 

